apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hd-exclusive
  name: hd-exclusive
# Consumed by mutating webhook
  annotations:
    cmk.intel.com/mutate: "true" # accepted values to trigger mutation: "true", "True", "1"
  namespace: cmk-namespace
spec:
  selector:
   matchLabels:
    app: hd-exclusive
  replicas: 0
  template:
    metadata:
      labels:
        app: hd-exclusive
    spec:
     serviceAccountName: cmk-serviceaccount
     containers:
      - name: hd-exclusive
        image: hrabhijith2/playhd:exclusive
        imagePullPolicy: Always
        ports:
         - containerPort: 5004
           hostPort: 5004
        env:
        - name: CMK_PROC_FS
          value: "/host/proc"
        resources:
         requests:
          cmk.intel.com/exclusive-cores: '1'
         limits:
          cmk.intel.com/exclusive-cores: '1'
        volumeMounts:
         - name: tmp
           mountPath: "/tmp"
         - mountPath: "/host/proc"
           name: cmk-host-proc
           readOnly: true
         - mountPath: "/opt/bin"
           name: cmk-install-dir
         - mountPath: "/etc/cmk"
           name: cmk-conf-dir
        securityContext:
         allowPrivilegeEscalation: true
         readOnlyRootFilesystem: true
         runAsNonRoot: false
         privileged: true
         capabilities:
          drop:
           - all
     volumes:
      - hostPath:
         path: "/tmp"
        name: tmp
      - hostPath:
      # Change this to modify the CMK installation dir in the host file system.
         path: "/opt/bin"
        name: cmk-install-dir
      - hostPath:
         path: "/proc"
        name: cmk-host-proc
      - hostPath:
       # Change this to modify the CMK config dir in the host file system.
         path: "/etc/cmk"
        name: cmk-conf-dir
     nodeSelector:
       kubernetes.io/hostname: "nuc01"
