apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cmk-lane-detection-exclusive
  name: cmk-lane-detection-exclusive
# Consumed by mutating webhook
  annotations:
    cmk.intel.com/mutate: "true" # accepted values to trigger mutation: "true", "True", "1"
  namespace: cmk-namespace
spec:
  selector:
   matchLabels:
    app: cmk-lane-detection-exclusive
  replicas: 0
  template:
    metadata:
      labels:
        app: cmk-lane-detection-exclusive
    spec:
     serviceAccountName: cmk-serviceaccount
     containers:
      - name: cmk-lane-detection-exclusive
        image: hrabhijith/lane-detection:exclusive
        ports:
         - containerPort: 5006
           hostPort: 5006
        env:
        - name: CMK_NUM_CORES
          value: "1"
        - name: CMK_PROC_FS
          value: "/host/proc"
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          cmk.intel.com/exclusive-cores: '1'
         limits:
          cmk.intel.com/exclusive-cores: '1'
        volumeMounts:
         - name: tmp
           mountPath: "/tmp"
         - mountPath: "/host/proc"
           name: cmk-host-proc
           readOnly: true
         - mountPath: "/opt/bin"
           name: cmk-install-dir
         - mountPath: "/etc/cmk"
           name: cmk-conf-dir
        securityContext:
         allowPrivilegeEscalation: true
         readOnlyRootFilesystem: true
         runAsNonRoot: false
         privileged: true
         capabilities:
          drop:
           - all
     volumes:
      - hostPath:
         path: "/tmp"
        name: tmp
     nodeSelector:
      kubernetes.io/hostname: "alderlake"
